### ISSUE TITLE
system(): use of /dev/kmsg misses early boot messages

### ISSUE THREAD

**Issue by dwfreed** [syslog-ng/syslog-ng#1360]
Due to the transport construction always seeking to the end of /dev/kmsg, syslog-ng misses all the kernel messages generated before it starts.  Ideally, syslog-ng would start at the start of /dev/kmsg at system boot, and then seek to the end for syslog-ng restarts.  I'm not sure how to incorporate this with the persist file, so for now I've just replaced system() in my config to what it expands to, and replaced /dev/kmsg with /proc/kmsg in that.

**Comment by nilathak** [comment]
Any update on this issue?

I still see this problem with 3.16.1 using OpenRC instead of systemd.
After changing the system() definition to
``unix-dgram("/dev/log" so_rcvbuf(8192));``
``file("/proc/kmsg" program-override("kernel") flags(kernel) keep-timestamp(no));``
all early boot messages are logged correctly.

The standard system() definition does not work:
``unix-dgram("/dev/log" so_rcvbuf(8192));``
``file("/dev/kmsg" program-override("kernel") flags(kernel) format(linux-kmsg) keep-timestamp(no));``

**Comment by gaborznagy** [comment]
Hi @nilathak!

Sorry for a late answer and thanks for the report with the details!
I think we have not verified this issue yet.

From the code it looks like something similar what @dwfreed described: we seek to the end of /dev/kmsg.
Also, what I see is we drop the usage of /proc/kmsg in favor of /dev/kmsg (if we can open /dev/kmsg).
I think we do this for a reason, so we need to investigate this further.

**Comment by dwfreed** [comment]
You have to seek during reopening of /dev/kmsg, otherwise you'll read messages you've already seen before, because /dev/kmsg always contains the entire contents of the kernel ring buffer.  /proc/kmsg is different, in that reading from it permanently consumes that information (like a pipe), so the start of the file is always the oldest message you haven't read.

**Comment by notlistening** [comment]
Having seen this issue too on Alpine using syslog-ng 2.28 I can see that both /dev/kmsg and /proc/kmsg are present. It seems that syslog-ng chooses /dev/ rather than /proc/. So you do loose early kernel messages in the current implementation. A possible fix in my situation is to specify in the system()  options which input location you wish to use.

**Comment by cerebrum** [comment]
Yes, I can confirm this issue. Gentoo default/linux/amd64/17.1/desktop/plasma profile is here. syslog-ng in openrc, i.e. w/o systemd, does not record dmesg _before syslog-ng startup_ under the default configuration. I have sys-apps/openrc-0.44.10, app-admin/syslog-ng-3.35.1 and sys-kernel/gentoo-sources-4.4.301 installed. No systemd there too. I had no dmesg in /var/log/messages for a long time. I solved that issue by the following changes inside /etc/syslog-ng/syslog-ng.conf:
```
#source src { system(); internal(); };
source src {
        unix-dgram("/dev/log");
        #format(linux-kmsg)
        file("/proc/kmsg" program-override("kernel") flags(kernel) multi-line-mode(indented) keep-timestamp(no));
        internal(); };
```

I've got these params from official documentation:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/administration-guide/27#TOPIC-1663254
It is said there: 

> on Linux, the so-rcvbuf() option of the system() source is automatically set to 8192.

So, so_rcvbuf(8192) addition isn't necessary.

After the above changes I've finally got dmesg log inside /var/log/messages.
I commented `format(linux-kmsg)` option because it gave me error messages in kernel log inside /var/log/messages.

**Comment by bazsi** [comment]
I've just rebooted my Ubuntu 20.04.02 server with kernel 5.4.0-96 and I can see early boot messages:

2022-02-02T09:01:01.303+01:00 mail kernel: microcode: microcode updated early to revision 0x28, date = 2019-11-12
2022-02-02T09:01:01.303+01:00 mail kernel: Linux version 5.4.0-96-generic (buildd@lgw01-amd64-051) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 (Ubuntu 5.4.0-96.109-generic 5.4.157)
2022-02-02T09:01:01.303+01:00 mail kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-96-generic root=UUID=4853d84d-faa5-4127-9b7d-223e4ae81fd2 ro reboot=acpi splash quiet nomdmonddf nomdmonisw console=tty1 console=ttyUSB0,115200n8 vt.handoff=7

The system is systemd based, so the system() source expands to:

```
    source {
systemd-journal();

    }; # source
```

Which means that early kernel messages are received through the journal.

In your case, systemd is not running, thus we decide which kernel source to use based on the result of this function:
```
static gboolean
_detect_linux_dev_kmsg(void)
{
  gint fd = open("/dev/kmsg", O_RDONLY);

  if (fd == -1)
    return FALSE;

  gboolean seekable = lseek(fd, 0, SEEK_END) != -1;
  gboolean pollable = _is_fd_pollable(fd);

  close(fd);
  return seekable && pollable;
}
```

Looking a bit further, /dev/kmsg is explicitly seeked to the end:

```
LogTransport *
log_transport_devkmsg_new(gint fd)
{
  if (lseek(fd, 0, SEEK_END) < 0)
    {
      msg_error("Error seeking /dev/kmsg to the end",
                evt_tag_str("error", g_strerror(errno)));
    }
  return log_transport_file_new(fd);
}
```

I looked at the git history why it was implemented this way, but the reason is probably so that you don't get a boot log at every syslog-ng restart/reload. This is unfortunate, /dev/kmsg could be position tracked like all other file sources.

**Comment by bazsi** [comment]
> I looked at the git history why it was implemented this way, but the reason is probably so that you don't get a boot log at every syslog-ng restart/reload. This is unfortunate, /dev/kmsg could be position tracked like all other file sources.

This is not true unfortunately. /dev/kmsg does not support lseek() as a file would. Position tracking is not impossible, but it would need to use the sequence numbers, returned by /dev/kmsg as part of the payload.

https://github.com/torvalds/linux/blob/master/Documentation/ABI/testing/dev-kmsg

> 		The output format consists of a prefix carrying the syslog
> 		prefix including priority and facility, the 64 bit message
> 		sequence number and the monotonic timestamp in microseconds,
> 		and a flag field. All fields are separated by a ','.
> 

By the look of it, it should have been created as an entirely new driver instead of adding it to the file source... Sigh.  The advantage of /dev/kmsg over /proc/kmsg are as follows:

- it never blocks. If there are multiple readers of /proc/kmsg, one can block causing logging to be stalled completely, which eventually leads to a whole system stop. There are workarounds for this case in syslog-ng, but there were continuous reports of this from time to time.
- it gives more details on kernel messages (e.g. proper timestamp, and name-value pairs)

I'd say the easiest solution of this on Gentoo/Alpine is to change https://github.com/syslog-ng/syslog-ng/blob/master/scl/system/plugin.conf upon installation.

In that file if you write something like this:

block source system() {
     unix-dgram("/dev/log" so_rcvbuf(8192));
     file("/proc/kmsg" program-override("kernel") flags(kernel) keep-timestamp(no));
};

This should swap out the system() source generated by the builtin system-source plugin and replace it with the content you add to this file. This way the config could remain "clean" while retaining the use of /proc/kmsg

**Comment by discapes** [comment]
i applied the following patch, since the nice formatting that `format(linux-kmsg)` is only available for /dev/kmsg. I don't mind the issue of restarting syslog-ng, since I don't do restart it except when restarting the system.

```patch
diff --git a/modules/affile/linux-kmsg.c b/modules/affile/linux-kmsg.c
index 8cc2c50..127749b 100644
--- a/modules/affile/linux-kmsg.c
+++ b/modules/affile/linux-kmsg.c
@@ -38,11 +38,11 @@
 LogTransport *
 log_transport_devkmsg_new(gint fd)
 {
-  if (lseek(fd, 0, SEEK_END) < 0)
-    {
-      msg_error("Error seeking /dev/kmsg to the end",
-                evt_tag_str("error", g_strerror(errno)));
-    }
+  // if (lseek(fd, 0, SEEK_END) < 0)
+  //   {
+  //     msg_error("Error seeking /dev/kmsg to the end",
+  //               evt_tag_str("error", g_strerror(errno)));
+  //   }
   return log_transport_file_new(fd);
 }
```
