### ISSUE TITLE
warning elimination: the rest

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#1965]
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The task is: add these warnings to the ENABLE_EXTRA_WARNINGS blocks, both for autotools and cmake. And fix these warnings.

It is not necessary to fix everything in one round. We can split further this ticket.

```
0    -Wbad-function-cast
1077 -Wconversion
655  -Wmissing-prototypes
220  -Wsign-compare
1455 -Wsign-conversion
0    -Wmissing-declarations
0    -Woverride-init
0    -Winline
144  -Wcast-qual
6    -Wformat-nonliteral -Wformat

```
(The numbers in the statistics are just an approximate)

Hint:
- autotools
Add this to configure: `../syslog-ng/configure CFLAGS="-Werror" --enable-extra-warnings ...`
- cmake
Add this to cmake call: `cmake ../syslog-ng -DENABLE_EXTRA_WARNINGS=yes -DCMAKE_C_FLAGS="-Werror" ...`

**Comment by furiel** [comment]
I updated the description with the remaining warnings from #1302.

**Comment by alltilla** [comment]
I can see that some of this are already fixed, but there's some which are yet to be fixed.

@furiel: Is it possible to make another round of `warning elimination` issues with the remaining flags? I mean, are the not-yet handled flags in game, still?
@vivinperis: If it is possible, would you care to create some issues about those flags? :)

**Comment by furiel** [comment]
I update the description, because me seems some of the warnings are fixed. Also, I am almost sure my statistics are wrong. According to `cloc $(git ls-files)`, we have `132350` lines of C code. I cannot believe that there are 5K sign conversion related warnings.

**Comment by vivinperis** [comment]
I'll look into it @alltilla

**Comment by furiel** [comment]
I updated the description. I gave another thought about the individual warnings, and I removed some:

- `-Waggregate-return`. 110 occurrences. Warns if a function returns a structure. We are using it in a lot of places. I think we cannot eliminate it reasonably It does not give too much trouble either, unless large size of data needs to be copied due to this.
- `-Wcast-qual`. 144 occurrences. Warns when you remove const keyword with a pointer casting.
- `-Wredundant-decls`. 92 occurrences. Warns if if anything is declared multiple times. Our grammar constructs (parsers, debug flags) fall this case. I think we cannot remove them easily, nor they cause too much trouble.
- `-Wmissing-field-initializers`. 706 occurrences. Warn if a structure’s initializer has some fields missing. We do this for all grammar keywords: `{ "monitor_method",     KW_MONITOR_METHOD },`. Generally, I think these usages are fine.
- `-Wsuggest-attribute=const`. 1 occurrence.
- `-Wsuggest-attribute=pure`. 3 occurrences. We do not do attributes in syslog-ng. One could experiment with it, but I would not enforce it at this point.
- `-Wformat-nonliteral`. 6 occurrences. Warns if if not a literal string is used for a function with a format string. Sometimes we want to build abstractions around such functions. These can lead to serious problems. On the other hand, I don't know if we want to eliminate them all.

@alltilla let me know if you disagree with anything.
Some warnings occur in large quantities. It would be great if we could split them further. I just don't know how.

**Comment by vivinperis** [comment]
@alltilla @furiel  Do I split the remaining warnings into individual issues or do them in groups?

**Comment by alltilla** [comment]
@furiel: I agree, thanks :) I had a doubt with `-Wcast-qual`, but it just seems impossible to fix in some places.
@vivin: I think one issue for one flag is okay for now, we might even divide single issues to multiple ones, as furiel suggested.

**Comment by furiel** [comment]
@Kokan I removed the `-Winline` from the list. Could you kindly check the remaining warnings if they are necessary or not, in your opinion? Also, I removed some warnings myself. Could you check that list too? https://github.com/syslog-ng/syslog-ng/issues/1965#issuecomment-617712819

**Comment by Kokan** [comment]
sure.
* `-Waggregate-return` sane compilers now support the aggregated return, the only other benefit would be as you suggested the speed. If this is going to prove to be the current bottleneck this might come in handy to remember having a warning. I agree not to use it for now.
* `-Wcast-qual` First of all I am biased with this one. This is not limited to conversion that remove const, but rather any unsafe type qualifier casting. From which mostly const the one we have in our code. With C11 (if ever) it also extends the list with `_Atomic` (based on llvm current state, it only handles const and volatile). I do not say this is *important* but would not discard as well.
* `-Wredundant-decls` I did not dig into this warning.
* `-Wsuggest-attribute=` Based on the description: "Warn about functions that might be candidates for attributes pure, const or noreturn or malloc."; this warning is not sound more like just static analysis, and do not really warn about potentially bad patterns but suggest annotation that compiler might use for optimisations.
* `-Wmissing-field-initializers` while the keyword could be dealt with easily so those are not concern, there are generated code violating this warning, and otherwise the default 0 value is pretty expected in syslog-ng context. but I would be fine merging changeset introducing this warning.
* ` -Wformat-nonliteral` without `-Wformat` and firends I do not see value in this warning, with `Wformat` it might be a nice ally. 
* `-Wmissing-declarations` and `-Wmissing-prototypes` These could help to detect some static functions, that would be useful.
* sign,float compare,conversion: I am not sure if we can manage to clear all of them, but would be happy to see it.
* `-Wbad-function-cast` I skipped to check this one also :(

**Comment by furiel** [comment]
Based on Peter's explanation and a short discussion IRL, we concluded to put these back.
```
-Wcast-qual
-Wformat-nonliteral -Wformat
```
These have some usefulness, so it's worth dealing with them with low priority.

**Comment by furiel** [comment]
Closing this old issue. This may have been outdated too. Let's open a fresh and updated ticket in case we need this.
