### ISSUE TITLE
Config objects preceded by an inline destination are ignored

### ISSUE THREAD

**Issue by MrAnno** [syslog-ng/syslog-ng#2820]
# syslog-ng

## Version of syslog-ng

syslog-ng v3.22.1

# Issue

The following configuration will not send any logs to `d_asd`:

```
@version: 3.22
destination d_asd {
	network("127.0.0.1" port(4448));
};

log {
	source { network(port(4444)); };
	destination {
		network("127.0.0.1" port(4447) );
	};
	destination(d_asd);
	flags(flow-control);
};
```

The cfg graph built from this config is incorrect. Changing the order of the 2 destinations (listing the inline destination last) fixes the issue.

## Root cause
Inline destinations are compiled as `sequences` (`cfg_tree_compile_sequence()`), where no multiplexer is created for other objects. In case of general/non-inline destinations (`cfg_tree_compile_reference()`), the multiplexer is there:

https://github.com/balabit/syslog-ng/blob/1742b11e5cfa6544ece38aaecde96e9b423d61c5/lib/cfg-tree.c#L842-L851

Unfortunately, it seems syslog-ng creates a new multiplexer for **every** non-inline destination instead of adding a `hop` to the previous one. I don't know the reason, but we could improve on this too.

**Comment by bazsi** [comment]
Hi,

The reason for multiplexers is that the next pointer for a non-inline
destination cannot be used. So the multiplexer is always inline, its list
of next hops should contain a reference to the destination group.

I think that the inline destinations being a sequence should not cause
problems.

We could discuss this via phone or slack or similar to find a good enough
solution.

László Várady <notifications@github.com> ezt írta (időpont: 2019. júl. 5.,
P 14:24):

**Comment by furiel** [comment]
Is it possible that the problem depends on the types of the config elements? I checked with an inline file destination and a network destination, and it works for me:

```
$ cat ../etc/tmp.conf 
@version: 3.24

options {
  time-reopen(5);
};

destination d_network {
    network("127.0.0.1" port(4447) template("NETWORK: $MESSAGE\n"));
};

log {
	source { example-msg-generator(); };
	destination { file(/dev/stdout template("FILE: $MESSAGE\n")); };
        destination(d_network);
	flags(flow-control);
};
$ nc -k -l 4447 &
[1] 8261
$ timeout 5 ./syslog-ng -Fe -f ../etc/tmp.conf 
[2019-10-22T08:34:25.696765] syslog-ng starting up; version='3.24.1.11.g126a19f'
[2019-10-22T08:34:25.696968] Syslog connection established; fd='11', server='AF_INET(127.0.0.1:4447)', local='AF_INET(0.0.0.0:0)'
FILE: -- Generated message. --
NETWORK: -- Generated message. --
FILE: -- Generated message. --
NETWORK: -- Generated message. --
FILE: -- Generated message. --
NETWORK: -- Generated message. --
FILE: -- Generated message. --
NETWORK: -- Generated message. --
FILE: -- Generated message. --
NETWORK: -- Generated message. --
[2019-10-22T08:34:30.671485] syslog-ng shutting down; version='3.24.1.11.g126a19f'
FILE: -- Generated message. --
NETWORK: -- Generated message. --
```

However, with the config example in the ticket, I also experience the problem.

**Comment by furiel** [comment]
After looking into the matter deeper here is what I found out.

If I swap the order of an inline and normal destination, the config graph looks substantially different.

Showing a few examples:
- inline file, referenced network version (the config I used int the previous comment)
![file-network](https://user-images.githubusercontent.com/11007226/67566561-65316800-f728-11e9-8ead-2a8d63668d42.png)

The file destination and the network destination are linked into the same chain serially. One would think how this can work at all. And the trick is that the `affile_dd_queue` function ends with a `log_dest_driver_queue_method(s, msg, path_options);`, that pushes forward the message in the chain.

- referenced network - inline file
If I swap the order, the two destinations are put to the two tips of a multiplexer:

![network-file](https://user-images.githubusercontent.com/11007226/67566733-cc4f1c80-f728-11e9-81a0-f02159628039.png)

- inline network - referenced network
So what is happening in case of the network-network version (the config that is posted in the issue)? The graph looks like this:
![network-network](https://user-images.githubusercontent.com/11007226/67566896-2b149600-f729-11e9-8fac-36d9978acd2c.png)

Technically it should look like one long chain (similar to the file-network graph), but the lower part is disjoint. It is disjoint at: https://github.com/syslog-ng/syslog-ng/blob./4b22d468eecf5fe111be0af49da061bbd0034e51/modules/afsocket/afsocket-dest.c#L546

That code expects `self->next_pipe` to be `null`, but it points to the lower part of the chain. After overwriting the link with the pointer of the logwriter, the chain is broken.

I was thinking how this should be resolved but I do not have any plan yet.

The analogous solution would be that instead of `log_pipe_append`, I would join the logwriter into the chain.  But that would mean the message should flow through `log_writer_queue`. So that to work I need to add a `log_dest_driver_queue_method`-ish call to the end of `log_writer_queue`. But `log_writer_queue` does kind of strange things to the message (possibly drops), so I do not think that is a good idea.

Another thing that feels a little off, that now no destinations attach their workers to themselves, because they might not be a terminal point in the graph. Conceptually, me feels natural that a destination should be a terminal point in the graph.

It also feels strange that if I change the order of two destinations, the config graph looks so differently (single chain vs fork).

@bazsi could you give me some hint how to fix this?

**Comment by MrAnno** [comment]
I also feel it is right that destinations are terminal nodes in the graph. We obviously don't chain sources, but we should not chain destinations either, they break flow control:

```
log {
	source { example-msg-generator(log-iw-size(5)); };
	destination {
		network("127.0.0.1" port(4444));
	};
	destination {
		network("127.0.0.1" port(4445));
	};
	flags(flow-control);
};
```
This config won't stop the source if the second destination is down. We really need the multiplexer here.

**Comment by MrAnno** [comment]
Sorry, I was not right about the flow control part, `add_ack()` is working properly without the multiplexer between destinations.
