### ISSUE TITLE
implement list search functionality in syslog-ng

### ISSUE THREAD

**Issue by jszigetvari** [syslog-ng/syslog-ng#2924]
Currently there is no out of the box solution in syslog-ng for searching in list data structures.
Some list functions are present, but even with them it is pretty awkward to search a specific value in a list.

There already is a list-count() template function that counts the element of the list passed in. (On a sidenote: given that we don't store the list's length anywhere, list-count() has to walk through the whole list each time it is invoked.)
Similarly to list-count() it would be feasible to create a template function to implement searching in a list.
It could take the list, the regex pattern, and possibly a starting position as an argument (and perhaps flags for the type of match for the filter (regex, literal, glob, prefix, substring, etc.), and would return with the index of the list element, where the pattern matches.)
Also, a reverse search functionality would likely be useful, similarly to the forward search described above.

**Comment by alltilla** [comment]
@jszigetvari 

I implemented a new template function, called `list-search()`, which returns the index of the first occurrence of a keyword in a list. It handles the start index, too.

Regarding the reverse or backwards search function: It is harder than it seems. Currently our list implementation is just a well formatted string, plus some convenient APIs which operate on them (by this, I do not mean the template functions, but the `ListScanner` class). We have a `list_scanner_scan_next()`, which in theory could have a `list_scanner_scan_prev()` pair, but it is a bit more complicated. `ListScanner` is based on the fact, that we are going forwards, and we are identifying escaped characters by the `\` character. Walking through the list backwards means going character by character backwards, which is hard because of the backslashes, where we jump backwards 2 characters. It surely can be done, but would take a bigger effort.

I would suggest an alternative for it: What if we had a `list-findall()` template function, which returns a list of indexes. The list would be monotonously increasing. Could that be useful to you? Or should I work on `list_scanner_scan_prev()`?

I did not investigate the type of match for the filter, yet.

**Comment by jszigetvari** [comment]
Hi Attila,

Good work. The list-search() functionality sounds in deed promising.
For my use case at the moment, the reverse search would not be necessary, it's just a type of functionality often enccountered around the topics of searching and arrays.
I know syslog-ng's lists are not arrays, but they are conceptually similar.

The list find-all() could also come in handy, however in that case I would still be faced with the problem that I would have to work with a list which will have an unknown number of elements, which I will have to traverse individually, and syslog-ng not offer any elegant way to iterate through a list at the moment.

For the moment let's forget the use case of backwards search. We can cross that bridge at a later time, if it's more convenient for you this way.

**Comment by alltilla** [comment]
Thanks for the response. I say let's keep the backwards search for later, if someone comes up with a use case, we can think about it again. I am going forward with the match type. :)

**Comment by bazsi** [comment]
Instead of implementing a (potentially very hard) backward parsing
functionality, I would simply add a $(list-reverse) function that allows
going backward. If you something more complicated I would opt for using the
embedded python interpreter instead.

**Comment by gaborznagy** [comment]
@jszigetvari  After reviewing #2955, I've created a little example, how can you use it.
What do you think?

config:
```
log {
  source { file("input2.xml" flags("no-parse")); };
  parser { xml(prefix(".xml.")); };
  rewrite { set("$(list-nth $(list-search foo ${.xml.EventData.Data}) ${.xml.EventData.Data})" value(HOST)); };
  destination(d_local);
};
```

And the result with format-json output (rfc3164 scope):
`{"PRIORITY":"notice","MESSAGE":"<EventData><Data>42</Data><Data>example data</Data><Data>foo</Data></EventData>","HOST":"foo","FACILITY":"user","DATE":"Dec  7 15:17:36"}`
It shows the original list in `MESSAGE`, and `HOST` is set to `foo`

**Comment by jszigetvari** [comment]
@gaborznagy Nice work Gábor!
Just one notice from my side: are we supposed to specify the regex pattern without any delimiters? What if the pattern has to contain a space character for instance? Shouldn't we at least force users to enclose the pattern with single quotes?
Furthermore, I assume the pattern in the example should have been VM-.* instead of HOST-.*, right? Or am I missing something?

**Comment by alltilla** [comment]
@jszigetvari `"$(list-search --mode pcre \"a b c\" '\"foo\",\"a b c\",\"baz\"')"` and  `"$(list-search --mode pcre 'a b c' '\"foo\",\"a b c\",\"baz\"')"` work perfectly, and return 1.

**Comment by jszigetvari** [comment]
@alltilla Sorry, the credit goes to you for making this happen.

Okay, then no problem. I was just looking at the example, and was unsure why there were no quotes around the pattern.
Please feel free to close this issue once your MR gets to master.

**Comment by gaborznagy** [comment]
Sorry about the config example error, I've corrected the pattern.
