### ISSUE TITLE
http output module handling of 400 Errors

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#2996]
## Description of the problem
Common misconfigurations of client or server side for the http module can result in 4XX errors. Presently these errors cause the queue contents to be dropped.

## Proposed solution
Change 4XX errors to behave as 5XX errors which can be retried

**Comment by szemere** [comment]
@furiel could you help me out with this topic? (Sorry for bothering you, this was my only trace: https://github.com/syslog-ng/syslog-ng/commit/f7cee51b70)

**Comment by furiel** [comment]
One thing worth mentioning is that retry still results in message loss. After 3 tries (3 by default) the message will still be dropped.

The reason I chose that heuristic was based on that 4XX errors are non-recoverable, and 5XX are temporary errors. Specially, for 404, I think it is good to drop the message.

At that time when I created that commit it did not occured to me: an interesting question is 401 and 403 (authorization kind of messages). In those cases we can do better: do a disconnect (`LTR_NOT_CONNECTED` in threaded destination terminology) instead of drop or error. With that, the messages would not be lost, just accumulate in a buffer. If the error is fixed, messages will be sent. Still, if the buffer becomes full, this will also lead to message loss. Ultimately, we cannot save the messages 100% percent, just choose how quickly to lose them (instantly, after 3 tries, or after buffer is full).

The ultimate solution would be to add different actions for each http error codes. I once started to work on this: https://github.com/furiel/syslog-ng/commits/http-onerror, but in the end I did not need the implementation, so I abandoned it.

The idea was that we have some (any reasonable default action map), and let users override the actions from configuration. There would be an on-error() option in http destination that describes the actions. Something like this `on-error(401 error-msg("unauthorized") action(drop))`

So yes, I agree that the situation can be improved.

**Comment by rfaircloth-splunk** [comment]
Some 4XX errors are recoverable with intervention for example 401 and 403 are generally due to expired or invalid authentication data. It does require admin intervention but once corrected data can be forwarded presuming persist queue was used. I prefer the buffer full option as it limits the damage of human error for example rotating a password header making a typo and restarting. The other condition is ALB misconfiguration I have seen 4XX errors that will occur temporarily.

Granted if the admin of the environment is not monitoring for lack of event flow we can't save everything but I think we can mitigate better for the transient and human errors.

**Comment by rfaircloth-splunk** [comment]
@furiel the on error configuration would be great to allow handling of problems like misbehaving ALBs

**Comment by furiel** [comment]
@rfaircloth-splunk I created a pull request to address the issue. You can followup here: https://github.com/syslog-ng/syslog-ng/pull/3007
