### ISSUE TITLE
Disk Queue application is inclear

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3003]
## Documentation version
3.24.1

## Incorrect section
When using disk queue or reliable disk queue with a destination such as http that supports workers it is in clear if the value of disk-buf-size is per worker thread or total for destination

**Comment by gaborznagy** [comment]
Hi @rfaircloth-splunk!

Http dest. uses a separate disk-buffer for each worker.

See our [admin guide](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/37#TOPIC-1298008) for additional information

workers option:
>   CAUTION:Hazard of data loss. When you use more than one worker threads together with disk-based buffering, syslog-ng OSE creates a separate disk buffer for each worker thread. This means that decreasing the number of workers can result in losing data currently stored in the disk buffer files. Do not decrease the number of workers when the disk buffer files are in use.

Since it is documented, I'm closing this ticket.
