### ISSUE TITLE
Socket keepalive settings disabled by default due to typo?

### ISSUE THREAD

**Issue by jburgess777** [syslog-ng/syslog-ng#3061]
I noticed that there is code in afsocket which looks like it should be setting a 60 second keepalive interval on the socket:

https://github.com/syslog-ng/syslog-ng/blob/master/modules/afsocket/socket-options-inet.c#L234
```
#if defined(TCP_KEEPTIME) && defined(TCP_KEEPIDLE) && defined(TCP_KEEPCNT)
  self->tcp_keepalive_time = 60;
  self->tcp_keepalive_intvl = 10;
  self->tcp_keepalive_probes = 6;
#endif
```
In practice these lines of code have no effect because the Linux header files do not define `TCP_KEEPTIME`. Looking earlier in the file, it looks like the intention was to test for `TCP_KEEPINTVL` instead, i.e.
```
diff --git a/modules/afsocket/socket-options-inet.c b/modules/afsocket/socket-options-inet.c
index f610a89cc..cc777bc94 100644
--- a/modules/afsocket/socket-options-inet.c
+++ b/modules/afsocket/socket-options-inet.c
@@ -231,7 +231,7 @@ socket_options_inet_new_instance(void)
   socket_options_init_instance(&self->super);
   self->super.setup_socket = socket_options_inet_setup_socket;
   self->super.so_keepalive = TRUE;
-#if defined(TCP_KEEPTIME) && defined(TCP_KEEPIDLE) && defined(TCP_KEEPCNT)
+#if defined(TCP_KEEPINTVL) && defined(TCP_KEEPIDLE) && defined(TCP_KEEPCNT)
   self->tcp_keepalive_time = 60;
   self->tcp_keepalive_intvl = 10;
   self->tcp_keepalive_probes = 6;
```
With the patch above applied the socket sends keepalive messages by default:
```
15:36:56.442303 IP 192.0.2.2.43210 > 192.0.2.1.6514: Flags [S], seq 341681766, win 29200, options [mss 1460,sackOK,TS val 82132 ecr 0,nop,wscale 7], length 0
15:36:56.442334 IP 192.0.2.1.6514 > 192.0.2.2.43210: Flags [S.], seq 219356288, ack 341681767, win 28960, options [mss 1460,sackOK,TS val 82132 ecr 82132,nop,wscale 7], length 0
15:36:56.442347 IP 192.0.2.2.43210 > 192.0.2.1.6514: Flags [.], ack 1, win 229, options [nop,nop,TS val 82132 ecr 82132], length 0
15:37:56.518541 IP 192.0.2.2.43210 > 192.0.2.1.6514: Flags [.], ack 1, win 229, options [nop,nop,TS val 97152 ecr 82132], length 0
15:37:56.518572 IP 192.0.2.1.6514 > 192.0.2.2.43210: Flags [.], ack 1, win 227, options [nop,nop,TS val 97152 ecr 82132], length 0
15:38:56.678541 IP 192.0.2.2.43210 > 192.0.2.1.6514: Flags [.], ack 1, win 229, options [nop,nop,TS val 112192 ecr 97152], length 0
15:38:56.678572 IP 192.0.2.1.6514 > 192.0.2.2.43210: Flags [.], ack 1, win 227, options [nop,nop,TS val 112192 ecr 82132], length 0
15:39:56.838544 IP 192.0.2.2.43210 > 192.0.2.1.6514: Flags [.], ack 1, win 229, options [nop,nop,TS val 127232 ecr 112192], length 0
15:39:56.838576 IP 192.0.2.1.6514 > 192.0.2.2.43210: Flags [.], ack 1, win 227, options [nop,nop,TS val 127232 ecr 82132], length 0
```
While this looks good, I see that the documentation states that keepalive is expected to be disabled by default and the parameters set to 0:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/so-keepalive
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/tcp-keepalive-time
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/tcp-keepalive-intvl
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/tcp-keepalive-probes

It is not clear to me whether this means that the code is working as intended and perhaps these lines of code should instead be deleted?

**Comment by MrAnno** [comment]
Hello,

That's definitely a typo. Nice catch!
The documentation, however, states exactly the opposite what the intention was in code:
`so_keepalive` option is enabled by default with some default parameters.

Because of the typo, our defaults are not set, but `so-keepalive()` should work as expected with the kernel's defaults (`tcp_keepalive_time`: The default value is 7200 seconds (2 hours) on Linux.)

I think we should
- fix the documentation (`so-keepalive()` is enabled by default)
- fix the typo you've found (+ document the "new" default parameters)
- maybe consider setting higher values as defaults.

**Comment by furiel** [comment]
As the code did not do keepalive (due to the typo), and it was also documented that the default is no keepalive: I think the best is to keep the default to false. For backward compatibility.

I agree the default values of the tuning parameters should be set to 60,10,6. I do not think it is necessary to go for the kernel defaults. Me seems the kernel defaults are too high for practical use.

@jburgess777 could you open a pull request with the fix? We happily accept contributions.
You do not need to deal with the documentation change. We will follow it up with the documentation team.

**Comment by MrAnno** [comment]
Your suggestion sounds good to me, I think it's better than mine, but we can't keep backward compatibility then.

> For backward compatibility.

This won't be true in that case. 
Unfortunately, `so-keepalive()` was enabled by default but with kernel default timers.

`7200,75,9` is not a good default, so maybe it would not even matter if we changed the old behavior and disabled `so-keepalive()` by default.

**Comment by bazsi** [comment]
I think we can change the defaults here. Enabling keepalive is just much
better for syslog traffic.

The only reason one could possibly want to disable it is bandwidth use, but
a keepalive packet is simply the size of the smallest tcp frame, which is
sent if the connection is otherwise idle.

So I would just enable it and communicate it as a fix.

**Comment by vatsal-encs** [comment]
@furiel : I have fixed the typo. So, the default values for `so-keepalive()` are 60,10,6 now.
