### ISSUE TITLE
Changes on a monitored file is not being transferred to the remote syslog server

### ISSUE THREAD

**Issue by ttrading** [syslog-ng/syslog-ng#3274]
# syslog-ng
## Version of syslog-ng
3.5.6-3.el7

## Platform
CentOS 7.7

We are trying to transfer the changes to a local file to our central syslog server. Syslog-NG is installed on a CentOS7.7 system. We pasted the following few lines in /etc/syslog-ng/syslog-ng.conf:

source s_logfile1 { file("/home/test/message_list.json" follow_freq(10) flags(no-parse)); };

destination dest { udp("XX.XX.XX.XX" port(514) template("<$PRI>$DATE $HOST o365\n")); };

log { source(s_logfile1); destination(dest); };

The messages we receive at the central syslog server only includes the hostname and the message tag which are: **dem1: o365**

there is no trace for any other information. We try to test the system by adding additional lines to the monitored file manually but had no luck:
echo "This is a test" >> /home/test/message_list.json

There is not much revealed under /var/log/messages. Where can we start?

Thanks

**Comment by gaborznagy** [comment]
Hello!

The reason you don't see any content of the monitored file is due to the used template() option.
The template() configures the syslog message's format (i.e. what would you like to ).
Your template() option misses the `$MSGHDR` and `$MSG` macros.

`By default, syslog-ng sends messages using the following template: `${ISODATE} ${HOST} ${MSGHDR}${MESSAGE}\n`. (The ${MSGHDR}${MESSAGE} part is written together because the ${MSGHDR} macro includes a trailing whitespace.)`

Also, please note:
If a message uses the IETF-syslog format (RFC5424), only the text of the message can be customized (that is, the $MESSAGE part of the log), the structure of the header is fixed.

For more details, let me recommend our Admin Guide:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/63#TOPIC-1431146

**Comment by MrAnno** [comment]
Please reopen this issue if you have further questions/comments.
