### ISSUE TITLE
Is there async with python-intercepter 

### ISSUE THREAD

**Issue by xx-zhang** [syslog-ng/syslog-ng#3384]
## Description of the problem

when add python-intercepter , the log-event will run not as not intercepter, so is there muti-process or async with the using of python module.

**Comment by szemere** [comment]
Hello @xx-zhang ,
 unfortunately I am not sure what you mean by "python-intercepter". Could you please explain your use-case in a more detailed way? Usually an example message, or just the "expected output" helps a lot.

Thank You in advance!
Laci

**Comment by xx-zhang** [comment]
@szemere i'm sorry that i don't describe it well , it's my conf hear . it mains python-destination, but i don't know it's aysnc or muti=process out of my python- destination. because when my logs many inserts, it sometimes can't opreate well. 

```
root@zeek:~# cat client/syslog-ng.conf
@version: 3.28
@include "scl.conf"

source s_zeek_http_log { file("/logs/http.log");  };


destination d_http_kafka {
    python(
        class("intercepter_v0.Py3HttpKafka")
            value-pairs(scope("selected-macros" "nv-pairs"))
    );
};

log { source(s_zeek_http_log); destination(d_http_kafka); };
```

**Comment by furiel** [comment]
In python destination: syslog-ng does not create threads, nor use the async library from python. You are free to create your own eventloop or threads, according to your needs. I am not aware of any technical limitation about it.

On the other hand, we do not have such tests that use eventloop or create threads. If you believe there is such problem with the python-binding, please share a **minimal** example (python code + configuration + example messages), so that we could reproduce and fix the bug.

From implementation point of view, with a bit of simplification:

syslog-ng creates a single-thread python environment,  which will host your code. First syslog-ng instantiates your class inside this environment, and then calls it's init method. The init method is provided by your code, so you may start an eventloop there.

When syslog-ng receives a message in any of their sources, the message will pass through the processing pipeline, and it will end up in the queue of the destination driver, that manages the python destination, still implemented in c. Then the python destination driver pops the message from the queue, and converts it into a python LogMessage. Then it uses the insert method you provided to pass this python LogMessage object to your code, still in the same thread. No python code is used except your insert method. All this is implemented through the `cpython` binding.

**Comment by xx-zhang** [comment]
@furiel thank you very much, you helped me a lot.
