### ISSUE TITLE
Error assertion failed on syslog-ng = 7.0.12 

### ISSUE THREAD

**Issue by seddikalaouiismaili** [syslog-ng/syslog-ng#3463]
Hi team , 

it is a pleasure to write to you, i need to discuss about syslog-ng issue .
we have an infrastructure composed of servers and client syslog-ng with failover mode .
Since a fews days we find this errors in the log of primary nodes : 
```
 ERROR:/syslog-ng/pe-builder-image/syslog-ng-pe-project-7-0/syslog-ng-core/lib/logpipe.h:339:log_pipe_queue: assertion failed: ((s->flags & PIF_INITIALIZED) != 0)
```
And after that, syslog-ng failed and systemd restart it . 

Do you have any suggession 

Regards
Seddik

**Comment by gaborznagy** [comment]
Hi @seddikalaouiismaili!

Thank you for opening a bug report.
I couldn't notice in your bug description that you are using Syslog-ng Premium Edition 7.
Please note that this channel is primarily for the Open Source Edition of Syslog-ng and it's working on a best effort basis, there is no guarantee to find and fix every reported bugs.
As you seem to have Syslog-ng Premium Edition I would suggest you to open a support ticket.
https://www.syslog-ng.com/support/

Regarding the crash you reported: we would need a full backtrace here to see if this bug is already fixed or not.
We have a couple of already fixed bugs with similar backtrace in OSE (e.g. [#3173](https://github.com/syslog-ng/syslog-ng/issues/3173) and [#1557](https://github.com/syslog-ng/syslog-ng/issues/1557)), but I can't tell you in which premium edition versions are those fixed. Syslog-ng Support can help in that case.
