### ISSUE TITLE
Driver 'program' should mask sensitive information

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#3475]
In my application I defined a program destination like this:

```
destination d_mongo_snat {
   program("/usr/bin/mongo --username=syslog-ng --password=secretPassword"
      template("... \n")
   );
};
```

You have a security flaw when you show statistics:

```
$ syslog-ng-ctl query get "dst.program.d_mongo_snat*" 

dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=secretPassword.dropped=0
dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=secretPassword.memory_usage=0
dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=secretPassword.processed=1408648
dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=secretPassword.queued=0
dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=secretPassword.written=1408648
```

syslog-ng should mask the password. Of course, syslog-ng cannot know whether program contains any sensitive information.
I would see two solutions:

- Introduce a flag, e.g. `hide-args()`. When set to true then syslog-ng uses only the command (up to first space character) without any arguments. In my example the statistics would look like this:
```
dst.program.d_mongo_snat#0./usr/bin/mongo.written=1408648
```

- Gather the program from process status, i.e. take result from `ps -ho args -p $pid`. When the called application is written properly and in a secure way, then it masked sensitive information like passwords. Tools like `mongo` shell, Oracle `sqlplus` or `mysql` hide such information.
In my example the statistics would look like this:
```
dst.program.d_mongo_snat#0./usr/bin/mongo --username=syslog-ng --password=xxxxxxxxxxx.written=1408648
```

**Comment by Kokan** [comment]
Using `ps` for that would be really hard if not impossible. As you have to make sure the application actually runs (it can stop at any time) while you do the query.
The `hide-args` could work, the only downside of that option that you loose the ability to differentiate between multiple instances of the same application.

The first idea works on top of your suggestion:
Instead of `hide-args` and truncating, there could be a new way of providing arguments to a program destination:
```
destination d_mongo_snat {
   program("/usr/bin/mongo  "
      argument-list(
           "--username=syslog-ng"
           secret("--password=secretPassword")
      )
      template("... \n")
   );
};
```
As one might guess the `secret()` is left out of stats.

The second is an old idea, providing `stats-name()` as a configuration option, with that you could replace the name displayed in stats.



I would also consider that the app should be changed to be safer, and could avoid password from command line, and ask properly protected password storage. That would make it much safer.

**Comment by Wernfried** [comment]
I also opened a case for mongo, because the password is even not hidden in `ps` (see https://jira.mongodb.org/browse/TOOLS-2768) They plan to support using a config file rather than command line argument. I agree, this will be the better solution.

You may keep this enhancement-request open as "nice to have" feature.

Thanks for your support
Wernfried

**Comment by Wernfried** [comment]
Feature introduced in mongoimport
