### ISSUE TITLE
PatternDB Support time parsing

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3544]
## Description of the problem
In many cases the "time" in the syslog header is not the correct "time" of the event as the source essentially is a relay system i.e. checkpoint and palo alto. Using pattern DB I can identify a string as time but then have to call a parser based on filter logic after we exist parserdb. 

## Proposed solution
Using values allow calling a date-parser with a format option

## Alternatives
extracting the field as .raw.time value and using date-parser triggered using a filter

**Comment by bazsi** [comment]
I would steer your solution to the "alternative"  you detailed in your request. Here's a bit of a background:

There was a time when the only classification/parsing framework in syslog-ng was the db-parser() with the intention of running messages through a database based classification engine and then process it by relatively simple rules in the syslog-ng configuration. Back then, the configuration only permitted the use of filters for conditional message routing. In a way all application specific parsing logic was supposed to go into the db-parser().

Fast forward 12-13 years, today application specific logic is to be encapsulated into application specific parsers (cisco-parser(), apache-parser(), fortigate-parser() etc). Each of these is free to use syslog-ng's parsers in a combination that makes sense for them. For instance, apache-parser() is csv-parser() based, which is a format that would be very difficult to implement in db-parser(). fortigate-parser() uses kv-parser() that extracts name=value fields from the messages.

If we were to use db-parser() in the original scope (e.g. all messages go through a database, classified and the field-extracted), then basically all features that make up the syslog-ng parser harness would need to be exposed via db-parser() as well. 

We didn't take this route, rather attempted to pull back the need for classification into the main logic (for instance we now have if-elif-else, conditional expressions, etc), and then once the classification is done, we apply the parser that is best equipped to parse a message in the knowledge of which application it belongs to. db-parser() is then useful in this context, sometimes the message is just NOT something that you can easily parse with csv-parser() or kv-parser(), in those cases db-parser() can be very handy, but again it would operate on a set of patterns that is application specific.

The classification problem (which application is sending this message so that I can parse app specific rules on it), is now a list of sequential if statements, which is slower than doing a large, unified db-parser() on the same message flow, but the idea was that we would rather introduce features in the configuration language that make these faster, rather than having to make the entire syslog-ng config syntax part of db-parser()'s (ugly) XML format.

With all that said, this idea is actually implemented in the app-parser() framework. app-parser() classifies/parses messages automatically relying on "application adapters". Here's the one for checkpoint:

```
application checkpoint[syslog-raw] {
    filter {
        # "syslog" format
        message("^(<[0-9]{1,3}>)1 .* CheckPoint ") or
        # "splunk" format
        message('^time=[0-9]+\|hostname=[a-zA-Z0-9-]+\|product=Firewall');
    };
    parser { checkpoint-parser(); };
};
```

Or the one for Cisco:

```
application cisco[syslog-raw] {
	filter { message(": %" type(string) flags(substring)); };
	parser { cisco-parser(); };
};
```

And the one for fortigate:
```
application fortigate[syslog-raw] {
	filter { message("^<[0-9]+>date="); };
        parser { fortigate-parser(); };
};

```

Classification is done by the filter{} piece, which is evaluated sequentially by app-parser(). Once the messages match the filter
expression, the block enclosed in parser{} is used. This is where you can rely on either built-in or compound parsers. The cisco-parser() stuff is quite lengthy (and unfortunately not perfect), but the one for fortigate is pretty simple:

```
block parser fortigate-parser(prefix('.fortigate.') template("$MSG")) {
	syslog-parser(flags(no-header) template(`template`));
	kv-parser(prefix(`prefix`) template("$MSG"));
	date-parser(format("%Y-%m-%d %H:%M:%S") template("${.fortigate.date} ${.fortigate.time}"));
};
```

This produces reusable and composable blocks of classification/parsing elements.

Today the number of such adapters is pretty low:

```
$ git grep ^application
checkpoint/plugin.conf:application checkpoint[syslog-raw] {
cim/adapter.conf:application cim[syslog] {
cisco/plugin.conf:application cisco[syslog-raw] {
fortigate/fortigate.conf:application fortigate[syslog-raw] {
iptables/iptables.conf:application iptables[syslog] {
junos/plugin.conf:application junos[syslog] {
netskope/plugin.conf:application netskope[syslog-raw] {
paloalto/panos.conf:application panos[syslog] {
sudo/sudo.conf:application sudo[syslog] {
websense/plugin.conf:application websense[syslog-raw] {
```

And with those numbers scalability has not become an issue. But if scalability is an issue, one can always improve the classification side, so that common applications wouldn't use an O(N) algorithm for classification. And for that we might even want to reuse the radix algorithm in db-parser(), provided the basis of the classification for a lot of applications is the content of the same field and when it's not, we can always fall back to a sequence of filters and O(N) complexity.

Hope this makes sense.

**Comment by rfaircloth-splunk** [comment]
Can you point me to doc on the application parser I could not find any good explanation of the syntax. It seems the regex-based approach would be slower than the radix tree approach

**Comment by alltilla** [comment]
`app-parser()` is not documented, not sure if it is intentional. Currently, its only user is `default-network-drivers()` source, which is documented, though.

A quick, not official option list:
 * `topic(<literal string>)`: REQUIRED. It is a filter for pre-set topic groups. Currently only `syslog` and `syslog-raw` is used (see the `git grep` in bazsi's comment above).
 * `auto-parse(<yesno>)`: OPTIONAL (default yes). Turns on or off the automatic classification and parsing. No need to set it.
 * `auto-parse-exclude(<literal string>)`: OPTIONAL. Blacklists applications. Matching is done via substring search.
 * `auto-parse-include(<literal string>)`: OPTIONAL. Whitelists applications. If not set, every application is allowed. Matching is done via substring search. (`auto-parse-exclude()` can override it.)

`<literal string>` is a string without quotation marks.
Don't forget to `@include "scl.conf"`, which has the applications for `app-parser()`.
You can check your preprocessed config with `./sbin/syslog-ng --preprocess-into=/dev/stdout`

I will ask around, about whether we forgot to document this or it is intentionally left out.

**Comment by rfaircloth-splunk** [comment]
I was able to brute force figuring out the app-parser framework and removed my use of patterndb
