### ISSUE TITLE
date parser incorrect sets seconds

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3598]
# syslog-ng
## Version of syslog-ng
3.29.1

## Platform
linux

# Issue
## Failure

When parsing a time stamp provided by a source without seconds (rare) the host clock seconds is presumed instead of 00
date-parser example
'%Y-%b-%d %I:%M %p%z

## Steps to reproduce
Parse any time stamp without a second while the system clock is not at a zero second

**Comment by bazsi** [comment]
Looking at the code the behavior is surprising, but it's true that if you
have multiple alternate formats, the value parsed that far is not reset to
default.

Do you have multiple formats in your date-parser()?

**Comment by rfaircloth-splunk** [comment]
just one in this case HP Printer's use this time format without seconds

**Comment by LittleFish33** [comment]
@bazsi 
Hi, I've looked at the related codes of date-parser, and I think this problem is caused by the `mktime()` function. 

Specifically, in `data-parser()` function,  the input text is first parsed to a `WallClockTime` object using the `_parse_timestamp_against_date_format_list` function. Next, `convert_and_normalize_wall_clock_time_to_unix_time_with_tz_hint()` is called, which convert the `WallClockTime` object to our target, a `UnixTime *` object. The `ut_sec` filed of the `UnixTime *` object is obtained by the `mktime()` function. However, the default value of the `WallClockTime` is -1:
```c++
// lines 108-122 from lib/timeutils/wallclocktime.h
.tm =                               \
      {                                 \
        .tm_year = -1,                  \
        .tm_mon = -1,                   \
        .tm_mday = -1,                  \
        .tm_wday = -1,                  \
        .tm_yday = -1,                  \
        .tm_hour = -1,                  \
        .tm_min = -1,                   \
        .tm_sec = -1,                   \
        .tm_isdst = -1,                 \
      },                                \
      .wct_gmtoff = -1,                 \
      .wct_zone = NULL,                 \
      .wct_usec = 0,                    \
```

In this case, if the second is not provided in the `_parse_timestamp_against_date_format_list` process, the converted timestamp will be one second less than the expected result and thus date parser incorrect sets seconds.

For instance, I tested it with Ubuntu and syslog-ng 3.31.1

The data-parser format:

```
date-parser(format("%Y-%b-%d %I:%M %p %Z") template("${MESSAGE}")); 
```

The `${MESSAGE}`：

```
2021-Mar-17 10:30 AM PST
```

The converted result (i.e., `${S_ISODATE}`)：

```
2021-03-17T10:29:59-08:00
```

I think this issue can be solved by adding a `filed_check` function after the `_parse_timestamp_against_date_format_list` function is called, which sets the unprovided field (such as the second filed in the example) to a more reasonable value than -1 (such as 0).

Is there a problem with my understanding? And can I work on this issue?

**Comment by bazsi** [comment]
Sure, this is absolutely reasonable and you are probably right.

Please open a pull request with your fix, and consider all the other
fields, which mktime might use and could remain unset after a call to
strptime(). Would be great if testing coverage would be added to the unit
test.

Thanks.
