### ISSUE TITLE
 Add EOS (Exactly Once Semantics) support to kafka-c destination driver

### ISSUE THREAD

**Issue by ikyrannas** [syslog-ng/syslog-ng#3614]
## Description of the problem
There is no current support for EOS in the kafka-c destination driver

## Proposed solution
The goal is to extend kafka-c destination driver with EOS by using the transactional producer API. Kafka destination uses librdkafka and [librdkafka](https://github.com/edenhill/librdkafka) supports Transactions from v1.4.0.

## Additional context
Tasks:
- Modify existing kafka destination driver
- Implement new test cases
- Documentation, blog post
librdkafka supports Exactly One Semantics (EOS) as defined in [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging). 

Proposed by: @lbudai

## Additional info
Is there any chance that leveraging the SSL and SASL (GSSAPI/Kerberos/SSPI, PLAIN, SCRAM, OAUTHBEARER) capabilities of librdkafka is of value at this point?

**Comment by Kokan** [comment]
The easy part of this issue is resolved in 3.33.2 via providing transactional API in kafka destination (https://github.com/syslog-ng/syslog-ng/pull/3681). Currently in syslog-ng there is no kafka source/consumer. The kafka EOS requires both kafka consumer and producer, so the offset can be committed in one transaction. I am closing this issue for two reasons:
* no kafka source 
* syslog-ng provides mechanism to prevent message loss

Once there is kafka source, and message loss, duplication is a concern this can be revisited.
