### ISSUE TITLE
Regex issue

### ISSUE THREAD

**Issue by Bigfoot0007** [syslog-ng/syslog-ng#3652]
# syslog-ng

Regex issue. I like to use regex101.com to test my regex, but many time, the regex works on regex101.com, but in syslog-ng match(). here some sample.

ex1:
OriMessage: `<13> 10.224.22.68 CEF:0|||||2021-04-09 01:35:22 TD-FW-core-Primary %%0123333eeeeeeeeeeeeee`
Regex:          `(.*?) CEF:0\|\|\|\|\|\d+-\d+-\d+ \d+:\d+:\d+ (.*?) %%`
can't match any.

ex2:

OriMessage: `<13> 10.224.22.68 Apr 16 16:06:34 10.224.22.68 Apr 16 16:06:34 seashrsah01 RSA-ESA-Alert:_RAS CEF:0|RSA|NetWitness ESA`
Regex:          `.* (.*?) (.*?) (.*?) (.*?) (.*?) RSA-ESA-Alert:_RAS CEF:0\|RSA\|`

can't match any.

**Comment by Kokan** [comment]
I tried the first example, and it works fine for me. Please share a minimal configuration that does not work for you.

```
@version: 3.31
@include "scl.conf"

log {

 source { example-msg-generator(template("<13> 10.224.22.68 CEF:0|||||2021-04-09 01:35:22 TD-FW-core-Primary %%0123333eeeeeeeeeeeeee") num(1)); };
 filter { match("(.*?) CEF:0\\|\\|\\|\\|\\|\\d+-\\d+-\\d+ \\d+:\\d+:\\d+ (.*?) %%" value("MESSAGE"));  };
 destination { file("/dev/stdout" template("${MESSAGE}\n")); };
};
```

**Comment by Bigfoot0007** [comment]
I use the version 3.5.6, the Redhat embed version

**Comment by Kokan** [comment]
I still think your issue is regarding quoting inside a string (sure I've never used 3.5.6 maybe it needs some extra step, that's kinda a dinosaur waiting for the meteorite).
1. upgrade and my config help
2. downgrade my configuration
3. share a configuration, input and expected output

I have a few other suspicion that could go wrong, but without having you provided  enough information it is hard to do.
(idea like, you do regex on `$MESSAGE` where the input is parsed, so the message does not contains `<12> 10.224...` part.)

**Comment by Kokan** [comment]
I've tried, and it seems to work for me. Please if this issue still persist reopen the issue with the minimal reproducible configuration included.
