### ISSUE TITLE
Support SSL_CONF_cmd() to configure advanced client tls options

### ISSUE THREAD

**Issue by mohitvaid** [syslog-ng/syslog-ng#3993]
## Description of the problem
For TLS configuration, unable to specify the signatureAlgorithms/clientSignatureAlgorithms.

## Proposed solution
Instead of using SSL_CTX_set_cipher_list()/SSL_CTX_set_ciphersuites the TLS configuration should use SSL_CONF_cmd

## Alternatives
NA

## Additional context
For certain compliance standards, say NIAP we need to limit Client-Hello's cipher-suites, signatureAlgs, clientSigntureAlgs, elliptic-curves and perform OCSP validation. Such features are not configurable via commands being currently in use (SSL_CTX_set_cipher_list()/SSL_CTX_set_ciphersuites)

See discussion in https://github.com/syslog-ng/syslog-ng/discussions/3983

**Comment by MrAnno** [comment]
Thanks for opening this issue.

I really like the idea of supporting `SSL_CONF_cmd` syntax in our configuration. This way, we don't need to worry about all the new OpenSSL configuration options that we've missed so far.

nginx and other web servers seem to support the same, for example:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_conf_command

Since we already have a lot of TLS options, there's a conflict between those and the proposed SSL_conf options. I think we should choose a simplistic approach to handle the conflict, for example, by always handling ssl_conf options with higher priority.

This might take a while, so until we implement this, we could add a traditional syslog-ng option for configuring signature algorithms based on [SSL_CTX_set1_sigalgs()](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set1_sigalgs.html).

**Comment by mohitvaid** [comment]
@MrAnno Thanks for looking into this.
Can we get some interim solution to this, may be as you mentioned based on SSL_CTX_set1_sigalgs()

We are blocked until then.

Also, I want to understand, does peer_verify(yes) takes care of OCSP flow as well?

**Comment by MrAnno** [comment]
@mohitvaid I will try to open a pull request in the late afternoon that adds a traditional option.

Furthermore, @OverOrion indicated that he might be interested in implementing the conf-command configuration function you mentioned.

> Also, I want to understand, does peer_verify(yes) takes care of OCSP flow as well?

OCSP stapling is currently not supported by syslog-ng's network sources/destinations, certificate revocation lists should be deployed instead (see the `crl-dir()` TLS option).

**Comment by mohitvaid** [comment]
Great @MrAnno , based on this. May I know by when I can get the GA build of this change? Any idea on timelines? Kindly update.

**Comment by MrAnno** [comment]
We usually release syslog-ng in 2-month cycles, the syslog-ng v3.37 release, for example, is planned for the end of May:
https://github.com/syslog-ng/syslog-ng/milestones

We don't have timelines for features requested by our community, but all contributions are welcome, and they are reviewed/tested/integrated on a best-effort level.

With all that being said, the sigalgs option will hopefully be part of the next release.

The complete `openssl-conf-cmd` feature might require some additional work, we'll let you know once we have a proposed implementation.

**Comment by MrAnno** [comment]
@mohitvaid #4000 adds 2 new TLS options, which can be used to restrict signature/hash algorithms specified in RFC5246 and RFC8446.

Let me know if you need deb/rpm packages for testing purposes.

**Comment by mohitvaid** [comment]
@MrAnno sure, please share the rpm package. We will validate and update. Thanks.

**Comment by MrAnno** [comment]
The mentioned options have been integrated into our main branch, they will be part of the next release.
I'm reopening this issue as the original request is about a `openssl-conf-cmd()`-based implementation.

https://github.com/syslog-ng/syslog-ng/issues/3993#issuecomment-1114719437
