### ISSUE TITLE
$if() does not work.

### ISSUE THREAD

**Issue by Roffild** [syslog-ng/syslog-ng#4020]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)
Config version: 3.29
Installer-Version: 3.30.1

## Platform
alpine 3.15

## Config
```
@version: 3.30
log {
source {
   channel {
      source {
         internal();
      };
      rewrite {
         set('LOG990', value('PGSEVERITY'));
         set('$(if ("${PGSEVERITY}" == "ERROR" or "${PGSEVERITY}" == "WARNING") "error" "info")', value("PGTEST"));

         set-severity('$(if (
         "${PGSEVERITY}" == "PANIC"
         or "${PGSEVERITY}" == "FATAL" or
         "${PGSEVERITY}" == "ERROR" or
         "${PGSEVERITY}" == "WARNING") "error" "info")');
      };
   };
};
destination {
   file("/home/neo/logs/${PROGRAM}/${DAY}-${PROGRAM}-${SEVERITY}.log",
        template("------------------${ISODATE}\nPGS=${PGSEVERITY} == ${PGTEST}\n"),
        create-dirs(yes),
        flush-lines(1)
   );
};
};
```
## Output
```
PGS=LOG990 == error 
```
Should be "info".

**Comment by bazsi** [comment]
Hi,

You will need to use the "eq" operator instead of "==" to get string based
comparison.

Actually I am working on a PR right now that will modify this to be more
intuitive, by using type information to decide how to compare two things,
but that's not yet merged.

Here is my blog post about the topic:
https://syslog-ng-future.blog/syslog-ng-4-theme-typing/

And here's the last part of my pull request, most of it has already gone in.

https://github.com/syslog-ng/syslog-ng/pull/3831

**Comment by bazsi** [comment]
@Roffild did this solve your problem?

**Comment by Roffild** [comment]
Replacing `==` with `eq` solved the problem.
