### ISSUE TITLE
$(format-json) always sorts the keys.

### ISSUE THREAD

**Issue by Roffild** [syslog-ng/syslog-ng#4026]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)
Config version: 3.29
Installer-Version: 3.30.1

## Platform
alpine 3.15

I want to read the log myself. But I also want to parse the log. That's why I use JSON.
```
set('$(format-json d="${R_ISODATE}" zlm="${PGSEVERITY}" m="${PGMSG}")', value("MESSAGE"));

# output:
{"zlm":"LOG","m":"  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit","d":"2022-05-26T10:33:37+03:00"}
```
$(format-json) always sorts the keys in *DESCENDING* order.

**Comment by ritikBhandari** [comment]
You mean descending order?

**Comment by Roffild** [comment]
> descending

yes

**Comment by bazsi** [comment]
hmm.. $(format-json) needs to sort the keys internally, but indeed it would be more logical to do it in ascending order. I am not sure if there's a reason for make it descending.

Checking the code it seems there was an explicit reason for doing so, our value-pairs subsystem normally sorts keys in ascending order, while the code that turns name-value pairs into a hierarchical structure reverses this sort explicitly.

Apart from a cosmetic standpoint, do you see any actual issues in this reverse sorting?

**Comment by Roffild** [comment]
I am against key sorting. I want to see the keys in my order.

Sort in descending order by default. Yes, I didn't expect that.

syslog-ng 3 (3.36.1)

**Comment by Roffild** [comment]
```
@version: 3.36
log {
   source {
      internal();
   };
   rewrite {
      # for test
      set('LOG:  listening on IPv4 address "0.0.0.0", port 5432 ', value("MESSAGE"));
   };
   parser {
      # https://github.com/syslog-ng/syslog-ng/issues/4027
      csv-parser(columns("PGSEVERITY", "PGMSG"), delimiters(":"), flags(strip-whitespace, greedy));
   };
   rewrite {
      set('$(format-json d="${R_ISODATE}" zlm="${PGSEVERITY}" m="${PGMSG}")', value("MESSAGE"));
   };
   destination {
      file("/tmp/sngtest.log", template("${MESSAGE}\n"));
   };
};
```
```
{"zlm":"LOG","m":"  listening on IPv4 address \"0.0.0.0\", port 5432 ","d":"2022-05-30T16:03:31+03:00"}
```

**Comment by bazsi** [comment]
Hi,

The sorting piece is required (though it can be argued that an ascending
sort would be nicer). It is required because we are collecting name value
pairs using multiple mechanisms (key=value in arguments, or a wildcard
query from the message, or the --scope argument).

We collect all name-value pairs and then convert all of those into JSON.

Since our internal name-value pairs are in a dotted format, the sorting is
needed so that we can convert them to a nested JSON structure.

I am not sure of why we do reverse sorting. I can imagine it covers an edge
case. Maybe @Gergely Nagy ***@***.***> has a
recollection. I couldn't find a hint in the git history or the code.

I could change it easily to do a forward sort instead, but that would
require touching a lot of the test suite, so I am reluctant to do it,
unless there's a strong use case.

**Comment by Roffild** [comment]
Now ASCENDING order would solve my problem.

I suggest adding the `$(format-json --no-sort-keys d=...)` flag.
This flag, after sorting in `value_pairs`, will write the data in the incoming order.
In `tf_json_append` and `tf_flat_json_append` add the iteration loop in the correct order.

**Comment by algernon** [comment]
It's [value-pairs doing the sorting](https://github.com/syslog-ng/syslog-ng/blob/66d8017a1198b15df72a58133756efee3dfb2755/lib/value-pairs/value-pairs.c#L455-L462), and it does so to build up the structured format.

The reason we sort is due to how the data is stored - or was stored back when value-pairs was initially written - internally. Internally, it has no structure, it's just a list of key-value pairs, and it is value-pairs that builds a tree out of that. To build a tree, we want to sort the flat list of dot-notated keys, so we can easily figure out where an object starts, and where it ends. And we sort in descending order to make that even easier.

e0e94a991e11e9e37f4cf26c6e3bbe433fb73538 is the commit where structured processing is introduced.

That's all the history I had the time to dig up right now. But the TLDR is that internally, value-pairs are/were a flat list with keys in dotted-notation format, and not a tree. So to turn a flat list into a structure, we had to walk the pairs, and build a tree from the destructured dotted-notation, and doing so was easiest when the list is sorted in a descending order.

To illustrate, lets say we have the following keys: `foo.bar.baz`, `foo.bar.quux` and `bar`. Sorted descending, that's `foo.bar.quux`, `foo.bar.baz`, and `bar`. When we iterate through that, we'll quickly see that `bar` has a different prefix, so we can close the previous object first. Of course, this does not necessitate descending order. What does, is that we may have keys such as: `foo.bar.quux`, `foo.bar.baz` and `foo.bar`, and we want `foo.bar` to override the other two. Descending order makes that trivial.

**Comment by algernon** [comment]
Right, I couldn't hold back, and digged a bit further. It turns out, we were simply using `strcmp` to sort initially. We flipped the order in a62140deab02fe8ec81dfb75ac4034a2ab413800, by the looks of it, but I can't really see why.

So the simple explanation might be that we needed sorting to build objects, and the order just happened by accident. That's equally plausible.

**Comment by bazsi** [comment]
I think that should be the explanation, when we have values within a prefix
and the prefix on its own.

E.g.

prefix.foo
prefix.bar
prefix

This would generate:

{"prefix":{"foo":"value of $prefix.foo","bar":"value of
$prefix.bar"},"prefix":"value of $prefix"}

As you can see there's a duplicate key in the top-level object, the first
being a nested object, the second a string with the same name.

The assumption is that in these cases the last takes precedence in any
parser (unless it checks for duplicate keys), which is a sane behavior in
this edge case.

Of course this is an edge case which shouldn't happen with data originally
created from JSON and we can argue that a name value structure like this is
not a really good practice.

With that I think it could make sense to specify ordering to value pairs in
these cases.

Thanks @Gergely Nagy ***@***.***> for the explanation.

I can't take this on for implementation but if you are willing to
contribute I can do the review and can also help in guiding the
implementation.

Cheers,
Bazsi

**Comment by bazsi** [comment]
The reason why syslog-ng sorts keys was explained and while I understand the reverse sorting is not necessarily the most intuitive choice, there's a reason for that. JSON is meant to be consumed by tools and for those, ordering of the keys is not important.

With that said, I am closing this issue.
