### ISSUE TITLE
New macro for "E" or parsed time

### ISSUE THREAD

**Issue by ryanfaircloth** [syslog-ng/syslog-ng#4146]
## Description of the problem
In many data sources a more correct time stamp is available in the payload of the message. For some destinations such as elastic or Splunk that time is preferred. While for other destinations the syslog header time is used. Have an additional time field allows both to be kept

## Proposed solution
Similar to R_ and S_ add a new macro set P_ in the message context.

**Comment by bazsi** [comment]
We currently have 3 sets of timestamps

R - for reception time
S - for the timestamp as extracted from the syslog header
P - processed time, has been used for the SSB indexer and was used to store the time the message was written to the underlying storage. Probably the time-series database was using this as its key (as neither R_ or S_ is guaranteed to be monotonic).

These are all represented as a 64bit counter of seconds since the epoch, a 32 bit value for usecs and a 32 bit value for the timezone offset.

These timestamps all get separately serialized into the disk buffer file.

When accessing these values, we have:
  * the R_* set of macros  for the reception time
  * the S_* set of macros for the timestamp
  * the P_* set of macros for the "processed" time. 
  * plus the C_* set of macros provide the actual time the template is being expanded.

I would want to avoid adding a new timestamp on top of the existing three, that changes the serialization format as well as increasing the storage requirement of a LogMessage both in memory and in the disk buffer file.

You can already specify which timestamp you want to parse into using the time-stamp() option of the date-parser(). That option however does not allow the selection of the P_ timestamp at the moment.

I think it would be possible to repurpose the P stamp, I would only have to expose it to the data-parser()'s time-stamp option and with that you could parse anything into it and also use it using the P_ set of macros. the SSB use-case would conflict with this usage somewhat, as SSB overwrites this timestamp as it stores the message on the disk, but this only happens at the very last stage when the message is serialized, freeing up the P_ timestamp for the entire input path and for anything but SSB's log storage backend. Honestly I am not even sure that that timestamp should have been stored in LogMessage in the first place that should have been part of the envelope that encapsulates a LogMessage within the logstore.

An alternative to this could be to improve support for our new DATETIME type so that timestamps could be stored simply in a regular name-value pair. Probably the only reason you can't do it today is that you don't have a template function that takes a DATETIME value and formats the timestamp using strftime() or similar.

Now as I think of it, maybe this would be the much better solution.

$(format-date "%Y-%M-%DT%h:%m:%s" ${timestamphere})

What do you think?

**Comment by jhg03a** [comment]
Instead of a whole new set of `[A-Z]*` macros, I think it would be clearer and easier if you could specify a prefix like with regex-parser.  That way you can use date-parser however you like for processing without impacting the underlying serialization differently than it already works today.  My use case is unpacking syslog messages with an embedded timestamp in the message in an odd timestamp format and trying to serialize it back out in ISO8601 in place.  At the moment I can't use the date-parser without clobbering all the S_* or R_* fields which I still need.

**Comment by bazsi** [comment]
This PR implements a different approach but should resolve this issue: https://github.com/syslog-ng/syslog-ng/pull/4319

1) With that PR, you can extract a timestamp using date-parser() into a name-value pair
2) this name value pair is stored in the format <sec>.<nsec>+TT:ZZ (e.g. timestamp with nsec resolution and a timezone offset), the type hint of this value is set to DATETIME
3) $(format-date) can take this name-value pair and you can use strftime() style formatting to generate the time information you want, in the original timezone or an overridden one, as you want.

Unfortunately strftime() does not support "%f" to represent the fractions of a second, so that does not work, but apart from that I consider this pretty much complete.

What do you think?

**Comment by bazsi** [comment]
Example:

Parse $whatever using strptime() format %s.%f into a value $foobar
```
        parser { date-parser(format("%s.%f") template('$whatever') value('foobar')); };
```

Format $foobar as a timestamp in a template:
```
    $(format-date '%Y-%m-%dT%H:%M:%S' $foobar)
```

**Comment by bazsi** [comment]
feedback appreciated.
