### ISSUE TITLE
Auth.log file size issue

### ISSUE THREAD

**Issue by Niba-nazar** [syslog-ng/syslog-ng#4157]
# syslog-ng
## Version of syslog-ng

syslog-ng --version
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision: 3.13.2-3
## Platform

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
## Debug bundle

# Issue
## Failure

Auth.log file is growing very fast. On checking could see docker related logs are also getting logged in auth.log file. How I can filter out those docker related logs from that.
## Steps to reproduce

Sep 28 10:14:34 docker audit[10773]: SYSCALL arch=c000003e syscall=59 success=no exit=-2 a0=7ffc9b00dd50 a1=558aa2d8ade0 a2=7ffc9b00e1f8 a3=7ffc9b010ec0 items=1 ppid=10000 pid=10773 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="xargs" exe="/usr/bin/xargs" key=(null)
Sep 28 10:14:34 docker audit: CWD cwd="/app"
Sep 28 10:14:34 docker audit: PATH item=0 name="/usr/lib/postgresql/9.6/bin/chown" nametype=UNKNOWN cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
Sep 28 10:14:34 docker audit: PROCTITLE proctitle=7861726773002D6E00310063686F776E006170703A617070
Sep 28 10:14:34 docker audit[10773]: SYSCALL arch=c000003e syscall=59 success=no exit=-2 a0=7ffc9b00dd50 a1=558aa2d8ade0 a2=7ffc9b00e1f8 a3=7ffc9b010ec0 items=1 ppid=10000 pid=10773 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="xargs" exe="/usr/bin/xargs" key=(null)
Sep 28 10:14:34 docker audit: CWD cwd="/app"
Sep 28 10:14:34 docker audit: PATH item=0 name="/usr/local/bundle/bin/chown" nametype=UNKNOWN cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
Sep 28 10:14:34 docker audit: PROCTITLE proctitle=7861726773002D6E00310063686F776E006170703A617070
Sep 28 10:14:34 docker audit[10773]: SYSCALL arch=c000003e syscall=59 success=no exit=-2 a0=7ffc9b00dd50 a1=558aa2d8ade0 a2=7ffc9b00e1f8 a3=7ffc9b010ec0 items=1 ppid=10000 pid=10773 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="xargs" exe="/usr/bin/xargs" key=(null)
Sep 28 10:14:34 docker audit: CWD cwd="/app"

**Comment by bazsi** [comment]
As far as I can see "docker" is the name of the host and not the name of
the software that generates said logs.

Audit logs are or might be associated with the auth.log destination by
default, you can exclude those by adding a filter to that destination.

For instance this defines a filter object that can be inserted into your
auth.log destination:


filter f_audit_excluded { not program("audit"); };

Then you can include this in the log statement that directs messages to
auth.log

log { source (whatever); filter(f_audit_excluded); destination
(authlog_destination); };


Please note that you need to use the correct names for the source and
destination that is present in your config.

You can also inline the filter expression if that's the only usage,
something like:

log {
  source (whatever);
  filter { not program("audit"); };
  destination (authlog_destination);
};

HTH,

**Comment by Niba-nazar** [comment]
@bazsi Thank you for the reply, let me try if this resolve my issue and will let you know

**Comment by bazsi** [comment]
1) you can include a timestamp in your log file name, so that syslog-ng automatically starts a new file, e.g.

file("/var/log/auth-$YEAR$MONTH$DAY.log");

Once the $DAY is changed, syslog-ng will start a new file and leaves the old one around. You will need to remove these files eventually, e.g. from cron.

As an alternative to this, you can have logrotate(3) or savelog(3) rotate your file every once in a while (e.g. from a cron job). Usually distros do have such a job already in place and logrotatedoes have a lot of features in terms of log rotation.

Also, there's an ongoing pull request in syslog-ng to support logrotate-like rotation, but it's not yet integrated (https://github.com/syslog-ng/syslog-ng/pull/4145/files)

2) To filter denied logs in a file, use a similar filter that matches "denied" logs and direct them into a separate file.

Honestly, the distro supplied default for log file layout is very traditional. What I'd actually do is that I'd put everything in one file first, and then create the different log files according to my taste/needs, instead of trying to keep up with what is supplied in the distro.

**Comment by Niba-nazar** [comment]
Hi @bazsi ,
Thank you for the quick reply. let me try this out and will let you know the progress

**Comment by Niba-nazar** [comment]
hi @bazsi ,

I tried to do like this but seems like no logs are writing to that file now

filter f_denied { host("docker") and match("failure" value("MESSAGE")); };

log {
source(s_auth);  filter(f_denied);
rewrite(r_csv_message);
destination(d_authdenied);
};

**Comment by bazsi** [comment]
You can debug a filter by enabling trace messages in a syslog-ng instance
that doesn't process production traffic and then send it a crafted message
using logger or netcat.

Syslog-ng also has statistics counters for each and every filters to see if
something was accepted/dropped by the filter.

You can query those counters using syslog-ng-ctl stats

**Comment by bazsi** [comment]
And you could also try the syslog-ng built in debugger, again running a
separate instance, using syslog-ng -i

With that syslog-ng will block until it receives a message and there are
commands to inspect the incoming message, evaluate filters, etc.

Let me know if the first two doesn't help, and I can help you with the
debugger.
