### ISSUE TITLE
Clients are blocked with disabled flow-control

### ISSUE THREAD

**Issue by LeoRuan** [syslog-ng/syslog-ng#4236]
# syslog-ng
## Version of syslog-ng
3.36.1

## Platform
ARM + Linux 5.10.y

## Configuration snippet
···
source s_src { system(); };
#destination d_debug_serial_port { file("/dev/ttyS0") };
destination d_debug_serial_port { pseudofile("/dev/ttyS0" template("${DATE} ${MSGHDR} ${MSG}\n")); };
log { source(s_src); destination(d_debug_serial_port ); };
···

# Issue
## Description
In my platform, log messages are stored in regular file in disk and also optionally go to a serial port. It is 'normal' case that nobody fetch log messages from serial port. That means the output buffer of the destination serial port is quickly full. This shall not block anything in storing messages to the regular file.

In my understanding on 'Managing incoming and outgoing message with flow-control' in Administration Guide, what I need is to create logpath (like configuration snippet in above) with disabling flow-control (it is disabled by default). Thus, the log messages are dropped in case the output buffer gets full. **But all clients are blocked at writing /dev/log in fact.**

As comparison, I had verified the behaviors is matched with expectation on destination network() and pipe(). When output buffer is full, the log messages are dropped.

**Comment by bazsi** [comment]
The file() destinations are somewhat special. They use a 'soft-flow-control' which means that even if flow-control is not enabled, they enact in flow-control unless there's a write error. If a write error occurs, this flow-control mechanism is lifted and you will lose messages as expected.

The reason for this behaviour is that losing messages to a file destination is not something that anyone expects, even if flow control is not enabled.

If there's an error (like the disk is full or the file cannot be opened), this automatic flow-control is lifted and we go back to non-flow-control mode.

The pseudofile() destination was originally aimed at writing files in /proc and /sys. So that driver is not using a queue at all, but rather will write messages to the file in question _within_ the source processing thread, assuming the write will always succeed. This means that you will probably block the reader once the serial buffer is full.

The pipe() driver should work for your use-case, the only issue being that it validates that the file in question is actually a named pipe and will not accept those without it.

If you are able to change the source and recompile, then can you check if with this patch, your use-case is covered? This remoces the check and pipe() should accept the serial device.

I'd be willing to add a serial() destination driver if this works out. It might even be possible to set various serial port properties through that driver, so no stty is needed.

```
diff --git a/modules/affile/named-pipe.c b/modules/affile/named-pipe.c
index 2a3408db2..72d645514 100644
--- a/modules/affile/named-pipe.c
+++ b/modules/affile/named-pipe.c
@@ -53,6 +53,7 @@ _prepare_open(FileOpener *self, const gchar *name)
       return TRUE;
     }
 
+#if 0
   if (!S_ISFIFO(st.st_mode))
     {
       msg_error("You are using the pipe() driver, underlying file is not a FIFO, it should be used by file()",
@@ -60,6 +61,8 @@ _prepare_open(FileOpener *self, const gchar *name)
       errno = EINVAL;
       return FALSE;
     }
+#endif
+
   return TRUE;
 }
 
```

**Comment by LeoRuan** [comment]
Yes, destination driver pipe() works well with serial device after applying your patch.
Thank you very much!
