### ISSUE TITLE
Embedded template function results in syntax error

### ISSUE THREAD

**Issue by protogen** [syslog-ng/syslog-ng#4449]
# syslog-ng
## Version of syslog-ng
3.38.1-1a

## Platform
Entware for armv7l (ASUSWRT-Merlin)

# Issue
## Failure
In a template definition, embedding a ```length``` function inside an ```if``` function causes a syntax error.

```
Error parsing filter expression, syntax error, unexpected LL_STRING, expecting ')' in <string>:1:11-1:17:

Error parsing config, Error compiling template, error=$(if) Error parsing conditional filter expression in /opt/etc/syslog-ng.conf:61:11-61:100:
58
59      template t_loghost {
60      #       template("<$PRI>1 $ISODATE $HOST $PROGRAM $(length \"$PID\") - - $MSG\n");
61---->         template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if ($(length \"$PID\") <= 0) '-' \"$PID\") - - $MSG\n");
61---->                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
62      #       template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if (\"$PID\" == '') '-' \"$PID\") - - $MSG\n");
63      };
64
```
The syntax above (line 60, ```length``` function only) passes syntax check and works correctly.
The syntax below (line 62, ```if``` function only) passes syntax check and works correctly.

Line 62 looks like an alternative, however the ```if``` condition only evaluates correctly when ```@version:``` is < 4.0.  When ```@version:``` is == 4.0 ```(\"$PID\" == '')``` evaluates to false even when ```$PID``` is empty.  I will log a separate bug report for this.

## Steps to reproduce
As shown above

**Comment by bazsi** [comment]
Thanks for the report. Sorry for having to fight with that syntax. I agree that it can be a pain.

This one works for me:

template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if ('$(length $PID)' <= 0) '-' \"$PID\") - - $MSG\n"));

This is never easy with backslashes, quotes and apostrophes playing a role at multiple levels:
 * the syslog-ng configuration language that uses them to delimit strings
 * the template language

The problem was that the conditional argument of the $(if) is a filter expression, similar to what you'd use in a filter {} block.

In filters, a string literal is considered a template which is expanded.

In steps:

```$(if <filter-expr> <true-value> <false-value>)```

The filter expression would be this if it was in the top-level of the config:

```"$(length $PID)" <= 0```

Note the quotes around $(length), within filter expressions, templates are denoted as quoted strings.

If we move this into the template() option, there are two issues:
* the filter expression contains spaces, which we need to escape so the $(if) considers it a single argument
* we need to make sure that the quotes get embedded into the template string itself.

The solution for the first, is to enclose the entire filter expression into parenthesises, as the template parser will consider balanced parenthesises as single arguments. But we could use quotes too, that'd be even more confusing.

The solution for the second is that the template() argument used the quote characters (") already to delimit string values, so if we want to embed another quote we need to backslash it, or use apostrophes instead.

With those two rules applied, this is what we get:

```template("$(if ('$(length $PID)` <= 0) <true-value> <false-value>)```

Which worked for as a part of a larger config:

```
@version: 4.0

log {

        source { tcp(port(2000)); };

        
        destination { file("/install/foobar" template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if ('$(length $PID)' <= 0) '-' \"$PID\") - - $MSG\n")); };
        
};
```

Other than that, one extra note, syslog-ng supports ${:-} style expansion like the bourne shell to supply default values. 

So ```${PID:-default}```  would expand to default if $PID is empty or unset. With that in mind, you could simplify the entire $(if) expression to ```${PID:--}```

Also, I am not sure why you are constructing the RFC5424 format via a template string, you could just use flags(syslog-format) with the destination or use a syslog() driver which does that automatically.

Is there a reason why you are doing this manually?

**Comment by protogen** [comment]
First of all, let me say thank you for giving such a comprehensive response.  The detail you have provided has been extremely helpful.

Your answer has highlighted my lack of understanding of the syslog-ng syntax.  I have read a lot of the manual, however I was unaware of one of the things you have mentioned, so clearly I need to read more.

I have tested both options you suggested (plus a variation).  My results are below.

**Option 1 - embedded length function using single quotes.  This passes syntax check and works correctly.**
```template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if ('$(length $PID)' <= 0) '-' \"$PID\") - - $MSG\n");```

**Option 2 - all single quotes inside double quotes (i.e. no escaped double quotes).  This passes syntax check and works correctly.**
```template("<$PRI>1 $ISODATE $HOST $PROGRAM $(if ('$(length $PID)' <= 0) '-' '$PID') - - $MSG\n");```

**Option 3 - Bourne shell style expansion.  This passes syntax check and works correctly.**
```template("<$PRI>1 $ISODATE $HOST $PROGRAM ${PID:--} - - $MSG\n");```

I will use option 3 as this is the simplest and neatest syntax.  I did not know syslog-ng supported Bourne shell style expansion of macros.  I went back and checked the manual, however I can't find any reference to this.  Can you point me to where this is mentioned?

Regarding options 1 and 2 - my Bourne and Bash coding experience really should have told me these were possible solutions.  I know that variables inside single quotes then inside double quotes get interpolated correctly.  I don't know why I didn't think of this.

Yes, you are spot on, I am manually constructing RFC5424.  Nice one noticing that :-).  The reason I'm doing this is because there are a couple of subtle differences between my template and `flags(syslog-format)` destination or `syslog()` driver.

The first difference is whitespace.  Pure RFC5424 sometimes passes a leading space in `$MSG`.

The second difference is the dash (`-`) in the case of an empty `$PID` value.

I am an old Unix sys admin (I started with Ultrix and SunOS).  The SunOS/Solaris syslog used a dash (`-`) if the PID value was empty.  I am simply trying to replicate that (because I like it).

Also, my home setup does the following...

`syslog-ng (remote devices) -> rsyslog (log server, custom template) ->` [swatchdog](https://github.com/ToddAtkins/swatchdog) `(log monitoring and alerting)`

... so my template is just a way of standardising my logging across multiple devices and servers.

There is one other thing I'll mention.  While the manual is very comprehensive, I do find it difficult to locate what I'm looking for.  I know the information is in there somewhere, I just always seem to have a hard time finding it.  I think this might be partly due to a difference in terminology.  I try to use search terms for what I think the functionality is called, but syslog-ng might call it something different.  Regardless, I'll keep reading.

Again, thank you for taking the time to clearly explain where I was going wrong.  It's rare to get such useful help these days.  :-)

**Comment by MrAnno** [comment]
Thank you for your extensive feedback.

>  While the manual is very comprehensive, I do find it difficult to locate what I'm looking for. I know the information is in there somewhere, I just always seem to have a hard time finding it.

We are working on an updated and hopefully more transparent and searchable version of syslog-ng/AxoSyslog manuals, it may be interesting for you:
https://axoflow.com/axosyslog-core-documentation-syslog-ng/
