### ISSUE TITLE
flags(final) not being applied

### ISSUE THREAD

**Issue by normelton** [syslog-ng/syslog-ng#4595]
# syslog-ng
## Version of syslog-ng
4.3.1

## Platform
Mac OS + Docker

# Issue
## Failure

Expected behavior:
- Filter messages containing "AA" into /tmp/output.txt
- Mark all messages as 'final', so that nothing goes into /tmp/unhandled.txt

Observed behavior:
- Messages containing "AA" are written to /tmp/output.txt
- Messages that don't contain "AA" are written to /tmp/unhandled.txt

I've read all the documentation I can find about message flow, particularly with embedded log statements, and don't understand why this is the case.

```
source s_file {
  file ("/tmp/input.txt");
};

log {
  source(s_file);

  log {
    filter {
      message("AA");
    };

    destination {
      file("/tmp/output.txt" template("$R_DATE $HOST: $MSG\n"));
    };
  };

  flags(final);
};

log {
  source(s_file);

  destination {
    file("/tmp/unhandled.txt" template("$R_DATE $HOST: $MSG\n"));
  };
};
```

**Comment by bazsi** [comment]
flags(final) means that if the message gets delivered along the specific log path then that delivery is considered final and no further log statements are processed on the same level. This is in contrast to the default behavior which directs syslog-ng to send a message to _all_ log paths if there are more than one on a specific level.

This "being delivered" condition is propagated to the parent log path as well. e.g. a message is considered delivered at the parent, if at least one of the log paths on a specific level delivered it.

What constitutes delivery is defined as: if a message traverses all the filters on a specific log path, thus matching all filters that could potentially drop it and thus gets to the end of a log {} statement, then that message is considered successful delivery.

**Let's consider your specific example. **

When I send a message with "AA" in it:
* the filter in the embedded log {} statement matches, thus the message gets delivered to output.txt. The message is considered delivered in the embedded log path.
* there is only one log {} statement on this level, so further deliveries are done.
* this "being delivered" condition is then propagated to the parent log path, which has flags(final) in it.
* since the embedded path did deliver, the entire log statement is considered delivered. flags(final) terminates the evaluation, so the next top-level log {} statement that has unhandled.txt in it is not even considered.

When I send a message without "AA" in it:
* the filter in the embedded log {} statement does NOT match, the message is not delivered to output.txt
* the embedded log {} statement in the first top-level log {} is not matching, thus the first log statement is considered not delivering
* with that syslog-ng continues with the next log {} statement at the top level, which does not have a filter in it, so all messages land in unhandled.txt

And this is exactly what happens:

```
$ echo "AA" | nc -q0 localhost 2000
$ syslog-ng-ctl stats prometheus | grep output_events_total.*delivered
syslogng_output_events_total{filename="/tmp/output.txt",driver="file",id="#anon-destination0#0",result="delivered"} 1
```

```
$ echo "BB" | nc -q0 localhost 2000
$ syslog-ng-ctl stats prometheus | grep output_events_total.*delivered
syslogng_output_events_total{filename="/tmp/unhandled.txt",driver="file",id="#anon-destination1#0",result="delivered"} 1
```


This behavior is useful in a number of ways. 

1) You can easily create complex routing with conditionals, so that syslog-ng tries the first completely matching path and ignoring the rest. This can be used to classify log messages to find the right format, for instance when multiple different devices send to the same port 514.

2) you can easily create "catchall" destination which capture messages at the end, in which case nothing else matches.

**Comment by bazsi** [comment]
@eldarnash maybe the docs on the log statements could use some refinements

**Comment by bazsi** [comment]
btw, syslog-ng also has if / else / elif statements, that might be easier to read, they are just a syntactic sugar around log statements, but simplify the config file a lot.

https://axoflow.com/docs/axosyslog-core/chapter-routing-filters/logpath/concepts-if-else-conditional-expressions/

Also, some (or most) of the syslog-ng devs lurk on this Discord server, where you can ask more interactively: https://discord.gg/E65kP9aZGm

**Comment by normelton** [comment]
First, thanks for the awesome reply. I agree there are some important details to understand here!

> When I send a message without "AA" in it:
> the embedded log {} statement in the first top-level log {} is not matching, thus the first log statement is considered not delivering

The message doesn't match the embedded log{} statement, agreed. But the outer log statement doesn't have any failing filters. In fact, it doesn't have any filters at all!

Is an outer log statement only considered "delivered" if all filters match, **and** at least one embedded log statement is also delivered?

I think I've managed to get our environment configured using if/elif/else clauses. I just want to understand the details here, and make our configuration as simple as possible!
