### ISSUE TITLE
Enhance eps_last_1h / eps_last_24h Metrics 

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#5013]
Some time ago you introduced these eps counters (event per second), they are very useful and I use them to monitor my application.

Let's assume in my application I have typically 1000 events per second. In case I get eps_last_1h less than 800 the system raises a warning.

Problem is, when statistics show for example `eps_last_1h=62` then I don't know whether this low number is caused by a problem I have to look about or because the process has just be started or because the stats have been reset.

I can check the start time of syslog-ng with `ps` command, however there is no possibility (at least I am not aware of any) to find out, when `syslog-ng-ctl stats --reset` was executed the last time.

Maybe it would be useful to add a counter like `reset_secs` which shows the number seconds since last reset or seconds since startup. Another solution would be a counter `eps_last_1m` showing the EPS value of the past 1 Minute.

Or do you have any other proposal to monitor the number of incoming messages?

Kind Regards
Wernfried

**Comment by bazsi** [comment]
The issue with those eps counters is that you don't really have the time dimension. There's no way to know which timespan they refer to. Also, they are updated once per minute, so I wouldn't consider them real time either.

The Prometheus style metrics "syslog-ng-ctl stats prometheus" will give you absolute counters instead of EPS values, which you can turn into eps in Prometheus or any other monitoring tool. And that would be my suggestion for monitoring log processing.

Then you can control what timespan you are more  interested in simply by running queries against Prometheus.

This project lets you connect the Prometheus style metrics to Prometheus:

https://github.com/axoflow/axosyslog-metrics-exporter

This is an end to end monitoring solution, showing how this can be deployed on kubernetes:

https://axoflow.com/axosyslog-observability-in-kubernetes/

**Comment by czanik** [comment]
Here is a simple Python script you can use as Prometheus exporter, if you have syslog-ng 4.1 or later: https://www.syslog-ng.com/community/b/blog/posts/syslog-ng-prometheus-exporter It has no external dependencies.
